/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import java.awt.event.*;
import java.util.*;

public class GUI4 extends javax.swing.JFrame {
    DefaultListModel<String> dlm = new DefaultListModel<>();
    List<String> listData = new ArrayList<>();
    Set<String> setData = new HashSet<>();
    Map<Integer, String> mapData = new HashMap<>();
    int mapKeyCounter = 0;

    /**
     * Creates new form GUI4
     */
    public GUI4() {
        initComponents();
        jListItem.setModel(dlm);
        updateAllCounts();
        
        jButtonSaveList.addActionListener((ActionEvent e) -> {
            saveToList();
        });

        jButtonInsertList.addActionListener((ActionEvent e) -> {
            insertFromList();
            });

        jButtonSaveSet.addActionListener((ActionEvent e) -> {
            saveToSet();
            });

        jButtonInsertSet.addActionListener((ActionEvent e) -> {
            insertFromSet();
            });

        jButton1.addActionListener((ActionEvent e) -> {
            saveToMap();
            } // Save to map
            );

        jButtonInsertMap.addActionListener((ActionEvent e) -> {
            insertFromMap();
            });

        jButtonAdd.addActionListener((ActionEvent e) -> {
            addItemToList();
            });

        jButtonUpdate.addActionListener((ActionEvent e) -> {
            updateSelectedItem();
            });

        jButtonDelete.addActionListener((ActionEvent e) -> {
            deleteSelectedItem();
            });

        jButtonClear.addActionListener((ActionEvent e) -> {
            clearAllItems();
            });
        }

    private void updateAllCounts() {
        jLabelDataList.setText("Data tersimpan = " + listData.size());
        jLabelDataSet.setText("Data tersimpan = " + setData.size());
        jLabelDataMap.setText("Data tersimpan = " + mapData.size());
    }

    private void addItemToList() {
        String item = jTextFieldItemNama.getText().trim();
        if (!item.isEmpty()) {
            dlm.addElement(item);
            jTextFieldItemNama.setText("");
        }
    }
    
    
    private void updateSelectedItem() {
        int selectedIndex = jListItem.getSelectedIndex();
        if (selectedIndex != -1) {
            String newItem = jTextFieldItemNama.getText().trim();
            if (!newItem.isEmpty()) {
                dlm.setElementAt(newItem, selectedIndex);
                jTextFieldItemNama.setText("");
            }
        }
    }

    private void deleteSelectedItem() {
        int selectedIndex = jListItem.getSelectedIndex();
        if (selectedIndex != -1) {
            dlm.remove(selectedIndex);
        }
    }
    
    private void clearAllItems() {
        dlm.clear();
    }

    private void saveToList() {
        listData.clear();
        for (int i = 0; i < dlm.size(); i++) {
            listData.add(dlm.getElementAt(i));
        }
        updateAllCounts();
    }
    
    private void insertFromList() {
        for (String item : listData) {
            if (!dlm.contains(item)) {
                dlm.addElement(item);
            }
        }
    }
    
    private void saveToSet() {
        setData.clear();
        for (int i = 0; i < dlm.size(); i++) {
            setData.add(dlm.getElementAt(i));
        }
        updateAllCounts();
    }

    private void insertFromSet() {
        for (String item : setData) {
            if (!dlm.contains(item)) {
                dlm.addElement(item);
            }
        }
    }
    
    private void saveToMap() {
    mapData.clear();
    mapKeyCounter = 0; // reset
    for (int i = 0; i < dlm.size(); i++) {
        mapData.put(mapKeyCounter++, dlm.getElementAt(i));
    }
    updateAllCounts();
}


    private void insertFromMap() {
        for (String item : mapData.values()) {
            if (!dlm.contains(item)) {
                dlm.addElement(item);
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jButtonSaveList = new javax.swing.JButton();
        jButtonInsertList = new javax.swing.JButton();
        jLabelDataList = new javax.swing.JLabel();
        jButtonSaveSet = new javax.swing.JButton();
        jButtonInsertSet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonInsertMap = new javax.swing.JButton();
        jLabelDataSet = new javax.swing.JLabel();
        jLabelDataMap = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelItemNama = new javax.swing.JLabel();
        jTextFieldItemNama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListItem);

        jButtonSaveList.setText("Save to list ->");

        jButtonInsertList.setText("<- Insert to list");

        jLabelDataList.setText("Data Tersimpan = ");

        jButtonSaveSet.setText("Save to set ->");

        jButtonInsertSet.setText("<- Insert to Set");

        jButton1.setText("Save to map ->");

        jButtonInsertMap.setText("<- Insert to lmap");

        jLabelDataSet.setText("Data Tersimpan =");

        jLabelDataMap.setText("Data Tersimpan = ");

        jButtonClear.setText("Clear");

        jButtonAdd.setText("Add");

        jButtonUpdate.setText("Update");

        jButtonDelete.setText("Delete");

        jLabelItemNama.setText("Item Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSaveList)
                                    .addComponent(jButtonInsertSet)
                                    .addComponent(jButtonSaveSet)
                                    .addComponent(jButtonInsertList)
                                    .addComponent(jButton1))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDataMap)
                                    .addComponent(jLabelDataSet)
                                    .addComponent(jLabelDataList)))
                            .addComponent(jButtonInsertMap)
                            .addComponent(jLabelItemNama)
                            .addComponent(jTextFieldItemNama)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClear)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonAdd)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonUpdate)
                        .addGap(41, 41, 41)
                        .addComponent(jButtonDelete)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabelDataList))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSaveList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonInsertList)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSaveSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonInsertSet))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabelDataSet)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabelDataMap)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInsertMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelItemNama)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldItemNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI4().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsertList;
    private javax.swing.JButton jButtonInsertMap;
    private javax.swing.JButton jButtonInsertSet;
    private javax.swing.JButton jButtonSaveList;
    private javax.swing.JButton jButtonSaveSet;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelDataList;
    private javax.swing.JLabel jLabelDataMap;
    private javax.swing.JLabel jLabelDataSet;
    private javax.swing.JLabel jLabelItemNama;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldItemNama;
    // End of variables declaration//GEN-END:variables
}
